### ISSUE TITLE
The overworld appears when bridging out too far

### ISSUE THREAD

**Issue by Anonymous941** [Minecraft-3DS-Community/MC3DS-Skyblock-Plus#2]
I went into creative, and suddenly the overworld starts abruptly appearing when going out too far

**Comment by Cracko298** [comment]
closed issue due to inactivity, assuming resolved.

**Comment by Anonymous941** [comment]
Maybe I'll fix it once the CDB files are understood, but this could also possibly be fixed by setting the world size to small

**Comment by Cracko298** [comment]
Hi, the reason their are so many CDB files in the first place is because it'll generate normal terrain, this forces the terrain to not spawn on first load/startup but ignores it when saved. Seems to only really care about the chunk/region you're currently in at that time. 

It's tied to the VDB files as unexplored from what I've gathered and because FWO doesn't use VDB files, when saved it overwrites terrain as it was never accessed at least to what the game believes.
